### ISSUE TITLE
JSONException: No value for send_data

### ISSUE THREAD

**Issue by rivizoft** [cloudipsp/android-sdk#15]
![image_2021-02-21_23-41-08](https://user-images.githubusercontent.com/24506318/108684918-4eb24100-7515-11eb-9cfd-07cb0aed4963.png)
При вызове `cloudipisp.pay()` на 506 строке в Cloudipsp.java приходит вообще другой ответ от сервера, где в json ответе нет ключа send_data. 
Использовал [тестовые реквизиты](https://docs.fondy.eu/ru/docs/page/2/). 
Из-за этой ошибки невозможно внедрить Fondy в приложение.

**Comment by rivizoft** [comment]
При попытке оплатить с тестовой карты получаем такой ответ от сервера, так как в ответе нет ключа `send_data`, то и приложение падает: 

```
I/Cloudipsp: Sent(https://api.fondy.eu/api/checkout/token):{"request":{"amount":"25","currency":"RUB","delayed":"N","lang":"ru","merchant_data":"[]","merchant_id":"1396424","order_desc":"lol","order_id":"vb_1614010922668","preauth":"N","required_rectoken":"N","response_url":"http:\/\/callback","verification":"N","verification_type":"amount"}}
I/Cloudipsp: Read: {"response": {"token": "4fdf23b0495d0f0ed44435f4e3d17647da843f43", "response_status": "success"}}
I/Cloudipsp: Sent(https://api.fondy.eu/api/checkout/ajax):{"request":{"card_number":"4444555566661111","cvv2":"790","email":"shirko49@mail.ru","expiry_date":"0622","payment_system":"card","token":"4fdf23b0495d0f0ed44435f4e3d17647da843f43"}}
I/Cloudipsp: Read: {"response": {"action": "redirect", "url": "https://pay.fondy.eu/test/psbank_redirect/1374848039/75dd437fd5aad4877c2e9f919bb86748a35ddd1a", "target": "_top", "response_status": "success"}}
W/System.err: com.cloudipsp.android.Cloudipsp$Exception$IllegalServerResponse: org.json.JSONException: No value for send_data
        at com.cloudipsp.android.Cloudipsp.runInTry(Cloudipsp.java:343)
W/System.err:     at com.cloudipsp.android.Cloudipsp.access$1600(Cloudipsp.java:51)
        at com.cloudipsp.android.Cloudipsp$Task.run(Cloudipsp.java:358)
    Caused by: org.json.JSONException: No value for send_data
        at org.json.JSONObject.get(JSONObject.java:389)
        at org.json.JSONObject.getJSONObject(JSONObject.java:609)
W/System.err:     at com.cloudipsp.android.Cloudipsp.checkoutContinue(Cloudipsp.java:506)
        at com.cloudipsp.android.Cloudipsp.checkout(Cloudipsp.java:483)
        at com.cloudipsp.android.Cloudipsp.access$000(Cloudipsp.java:51)
        at com.cloudipsp.android.Cloudipsp$1.runInTry(Cloudipsp.java:103)
W/System.err:     at com.cloudipsp.android.Cloudipsp.runInTry(Cloudipsp.java:333)
```
